imports:
    - { resource: config_dev.yml }
    - { resource: services_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
  disable_delivery: true

knp_gaufrette:
  adapters:
    campaign_photos_local:
      local:
        directory: "%kernel.root_dir%/uploads/tests/"
        create:     true

  filesystems:
    campaign_photos:
      adapter: "%oloy.campaign.photos_adapter%"
      alias: campaign_photos_filesystem
