imports:
    - { resource: "@OpenLoyaltyCoreBundle/Resources/config/config.yml"}

    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    storage_suffix: "_%kernel.environment%"
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

framework:
    #esi:             ~
    translator:      { fallbacks: ['%locale%'] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

swiftmailer:
    transport:  '%mailer_transport%'
    host:       '%mailer_host%'
    username:   '%mailer_user%'
    password:   '%mailer_password%'
    port:       '%mailer_port%'
    encryption: '%mailer_encryption%'

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                server_version: "%database_version%"
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

broadway:
    event_store: oloy.dbal.event.store.concurrency
    read_model: oloy.read_model.repository.factory

nelmio_api_doc:
    sandbox:
        request_format:
            method: accept_header

jms_serializer:
    visitors:
        json:
            options: JSON_PRETTY_PRINT
    metadata:
      auto_detection: true
      debug: true

fos_rest:
    versioning: true
    routing_loader:
        include_format: true
        default_format: json
    param_fetcher_listener: force
    allowed_methods_listener: true
    disable_csrf_role: ROLE_USER
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }

    view:
        view_response_listener: 'force'
        formats:
            json: true

lexik_jwt_authentication:
    private_key_path: "%jwt_private_key_path%"
    public_key_path:  "%jwt_public_key_path%"
    pass_phrase:      "%jwt_key_pass_phrase%"
    token_ttl:        "%jwt_token_ttl%"

nelmio_cors:
    paths:
      '^/api/':
          allow_origin: ['*']
          allow_headers: ['*']
          allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
          max_age: 3600
          forced_allow_origin_value: '*'

gesdinet_jwt_refresh_token:
    ttl_update: true
    user_provider: oloy.user.all_users_provider

monolog:
    handlers:
        # this "file_log" key could be anything
        file_log:
            type: stream
            path: "%kernel.logs_dir%/plugin.log"
            # log *all* messages (debug is lowest level)
            level: debug
            channels: [plugins]

knp_doctrine_behaviors:
    translatable: true

a2lix_translation_form:
    locale_provider: OpenLoyalty\Bundle\TranslationBundle\Provider\A2lixLocaleProvider

doctrine_migrations:
    namespace: OpenLoyalty\Migrations
