# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: true

    role_hierarchy:
        ROLE_SELLER:      ROLE_USER
        ROLE_PARTICIPANT: ROLE_USER
        ROLE_ADMIN:       ROLE_USER
    encoders:
        OpenLoyalty\Bundle\UserBundle\Entity\User: bcrypt

    providers:
        master_admin_provider:
            id: OpenLoyalty\Bundle\UserBundle\Service\MasterAdminProvider
        admin_provider:
            id: oloy.user.admin_provider
        customer_provider:
            id: oloy.user.customer_provider
        seller_provider:
            id: oloy.user.seller_provider
    firewalls:
        admin_login:
            pattern:  ^/api/admin/login
            stateless: true
            anonymous: true
            provider: admin_provider
            form_login:
                check_path:               /api/admin/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        customer_login:
            pattern:  ^/api/customer/login
            stateless: true
            anonymous: true
            provider: customer_provider
            form_login:
                check_path:               /api/customer/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        seller_login:
            pattern:  ^/api/seller/login
            stateless: true
            anonymous: true
            provider: seller_provider
            form_login:
                check_path:               /api/seller/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        refresh:
            pattern:  ^/api/token/refresh
            stateless: true
            anonymous: true
        settings_choices:
            pattern:  ^/api/settings/choices
            stateless: true
            anonymous: true
        self_registration:
            pattern:  ^/api/customer/self_register
            stateless: true
            anonymous: true
        activate_account:
            pattern:  ^/api/customer/activate
            stateless: true
            anonymous: true
        password_reset:
            pattern:  ^/api/password/reset
            stateless: true
            anonymous: true
        customer_password_reset:
            pattern:  ^/api/customer/password/reset.*
            stateless: true
            anonymous: true
        customer_resend_code:
            pattern:  ^/api/customer/customer-phone/send-sms-code
            stateless: true
            anonymous: true
        customer_check:
            pattern:  ^/api/customer/check
            methods: ["GET"]
            stateless: true
            anonymous: true
        campaign_brand_icon:
            pattern:  ^/api/campaign/([a-zA-Z\-0-9]+)/brand_icon
            methods: ["GET"]
            stateless: true
            anonymous: true
        campaign_photo:
            pattern:  ^/api/campaign/([a-zA-Z\-0-9]+)/photo
            methods: ["GET"]
            stateless: true
            anonymous: true
        earning_rule_photo:
            pattern:  ^/api/earningRule/([a-zA-Z\-0-9]+)/photo
            methods: ["GET"]
            stateless: true
            anonymous: true
        level_photo:
            pattern:  ^/api/level/([a-zA-Z\-0-9]+)/photo
            methods: ["GET"]
            stateless: true
            anonymous: true
        settings_photo:
            pattern:  ^/api/settings/photo/(logo|small-logo|hero-image|admin-cockpit-logo|client-cockpit-logo-big|client-cockpit-logo-small|client-cockpit-hero-image)
            methods: ["GET"]
            stateless: true
            anonymous: true
        settings_logo:
            pattern:  ^/api/settings/logo
            methods: ["GET"]
            stateless: true
            anonymous: true
        settings_small_logo:
            pattern:  ^/api/settings/small-logo
            methods: ["GET"]
            stateless: true
            anonymous: true
        settings_hero_image:
            pattern:  ^/api/settings/hero-image
            methods: ["GET"]
            stateless: true
            anonymous: true
        settings_conditions_file:
            pattern:  ^/api/settings/conditions-file
            methods: ["GET"]
            stateless: true
            anonymous: true
        settings_conditions_file_pdf:
            pattern:  ^/api/settings/terms-conditions
            methods: ["GET"]
            stateless: true
            anonymous: true
        settings_activation_method:
            pattern:  ^/api/settings/activation-method
            methods: ["GET"]
            stateless: true
            anonymous: true
        doc:
            pattern:  ^/doc
            stateless: true
            anonymous: true
        translations:
            pattern:  ^/api/translations
            stateless: true
            anonymous: true
        seller_api:
            pattern:   ^/api/seller
            stateless: true
            provider: seller_provider
            lexik_jwt: ~
            guard:
                authenticators:
                    - oloy.user.guard.token
                entry_point: oloy.user.guard.token
        customer_api:
            pattern:   ^/api/customer
            stateless: true
            provider: customer_provider
            lexik_jwt: ~
            guard:
                authenticators:
                    - oloy.user.guard.token
                entry_point: oloy.user.guard.token
        settings_css:
            pattern:  ^/api/settings/css
            methods: ["GET"]
            stateless: true
            anonymous: true
        admin_campaign_featured:
            pattern:  ^/api/campaign/public/available
            methods: ["GET"]
            stateless: true
            anonymous: true
        admin_api:
            pattern:   ^/api
            stateless: true
            provider: admin_provider
            lexik_jwt: ~
            guard:
              authenticators:
                - oloy.user.guard.token
              entry_point: oloy.user.guard.token
        main:
            pattern: ^/
            anonymous: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/api/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/admin/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/campaign/public/available, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ["GET"] }
        - { path: ^/api/customer/self_register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/customer/activate/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/campaign/([a-zA-Z\-0-9]+)/photo, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ["GET"] }
        - { path: ^/api/campaign/([a-zA-Z\-0-9]+)/brand_icon, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ["GET"] }
        - { path: ^/api/campaignCategory(/[a-zA-Z\-0-9]+)?, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ["GET"] }
        - { path: ^/api/earningRule/([a-zA-Z\-0-9]+)/photo, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ["GET"] }
        - { path: ^/api/level/([a-zA-Z\-0-9]+)/photo, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ["GET"] }
        - { path: ^/api/password/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/customer/password/reset.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/customer/customer-phone/send-sms-code, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/customer/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/customer/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/customer/check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/seller/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/seller/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/settings/choices, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/settings/photo/(logo|small-logo|hero-image|admin-cockpit-logo|client-cockpit-logo-big|client-cockpit-logo-small|client-cockpit-hero-image), roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ["GET"] }
        - { path: ^/api/settings/logo, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ["GET"] }
        - { path: ^/api/settings/small-logo, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ["GET"] }
        - { path: ^/api/settings/hero-image, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ["GET"] }
        - { path: ^/api/settings/conditions-file, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ["GET"] }
        - { path: ^/api/settings/terms-conditions, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ["GET"] }
        - { path: ^/api/settings/activation-method, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ["GET"] }
        - { path: ^/api/settings/css, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ["GET"] }
        - { path: ^/api/translations, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
