services:
    _defaults:
        public: true

    oloy.pagination:
        alias: OpenLoyalty\Bundle\PaginationBundle\Service\Paginator
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    ol.settings.form_type.settings:
        alias: OpenLoyalty\Bundle\SettingsBundle\Form\Type\SettingsFormType
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    ol.settings.form_type.customers_indentification_priority:
        alias: OpenLoyalty\Bundle\SettingsBundle\Form\Type\CustomersIdentificationPriority
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    ol.settings.manager:
        alias: ol.doctrine_settings.manager
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    ol.doctrine_settings.manager:
        alias: OpenLoyalty\Bundle\SettingsBundle\Service\GeneralSettingsManager
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    ol.settings.validator.not_used_key:
        alias: OpenLoyalty\Bundle\SettingsBundle\Validator\Constraints\NotUsedKeyValidator
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    ol.settings.validator.unique_key:
        alias: OpenLoyalty\Bundle\SettingsBundle\Validator\Constraints\UniqueKeyValidator
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.settings.logo_uploader:
        alias: OpenLoyalty\Bundle\SettingsBundle\Service\LogoUploader
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.activation_code_manager:
        alias: OpenLoyalty\Bundle\ActivationCodeBundle\Service\ActivationCodeManager
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.action_token_manager:
        alias: OpenLoyalty\Bundle\ActivationCodeBundle\Service\ActionTokenManager
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    open_loyalty.sms.dummy:
        alias: OpenLoyalty\Bundle\ActivationCodeBundle\Service\DummySmsApi
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.activation_method.email:
        alias: OpenLoyalty\Bundle\ActivationCodeBundle\Method\EmailActivationMethod
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.activation_method.sms:
        alias: OpenLoyalty\Bundle\ActivationCodeBundle\Method\SmsActivationMethod
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.activation_code.alpha_num:
        alias: OpenLoyalty\Bundle\ActivationCodeBundle\Generator\AlphaNumericCodeGenerator
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.activation_code.num:
        alias: OpenLoyalty\Bundle\ActivationCodeBundle\Generator\NumericCodeGenerator
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.campaign.serialization_listener:
        alias: OpenLoyalty\Bundle\CampaignBundle\Event\Listener\CampaignSerializationListener
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.earning_rule.listener:
        alias: OpenLoyalty\Bundle\EarningRuleBundle\Event\Listener\EarningRuleSerializationListener
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.import.importer.xml_importer:
        alias: OpenLoyalty\Bundle\ImportBundle\Importer\XMLImporter
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.level.photo_uploader:
        alias: OpenLoyalty\Bundle\LevelBundle\Service\LevelPhotoUploader
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.transaction.form_handler.edit_transaction_labels:
        alias: OpenLoyalty\Bundle\TransactionBundle\Form\Handler\EditTransactionLabelsFormHandler
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.transaction.form_handler.append_labels_to_transaction:
        alias: OpenLoyalty\Bundle\TransactionBundle\Form\Handler\AppendLabelsToTransactionFormHandler
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.transaction.form_handler.manually_assign_customer_to_transaction:
        alias: OpenLoyalty\Bundle\TransactionBundle\Form\Handler\ManuallyAssignCustomerToTransactionFormHandler
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.user.form_handler.customer_edit:
        alias: OpenLoyalty\Bundle\UserBundle\Form\Handler\CustomerEditFormHandler
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.email.settings:
        alias: OpenLoyalty\Bundle\EmailSettingsBundle\Service\EmailSettings
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.points.account.repository.points_transfer_details:
        alias: OpenLoyalty\Component\Account\Domain\ReadModel\PointsTransferDetailsRepository
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.campaign.read_model.repository.campaign_bought:
        alias: OpenLoyalty\Component\Campaign\Infrastructure\Repository\CampaignBoughtElasticsearchRepository
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.transaction.read_model.repository.transaction_details:
        alias: OpenLoyalty\Component\Transaction\Infrastructure\Repository\TransactionDetailsElasticsearchRepository
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.transaction.read_model.projector.transaction_details:
        alias: OpenLoyalty\Component\Transaction\Domain\ReadModel\TransactionDetailsProjector
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.user.form_type.customer_registration:
        alias: OpenLoyalty\Bundle\UserBundle\Form\Type\CustomerRegistrationFormType
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.analytics.voter.analytivs:
        alias: OpenLoyalty\Bundle\AnalyticsBundle\Security\Voter\AnalyticsVoter
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.user.level_id_provider:
        alias: OpenLoyalty\Bundle\UserBundle\Service\OloyLevelIdProvider
        deprecated: The "%service_id%" service is deprecated since 2.8.0

    oloy.earning_rule.photo_uploader:
        alias: OpenLoyalty\Bundle\EarningRuleBundle\Service\EarningRulePhotoUploader
        deprecated: The "%service_id%" service is deprecated since 3.1.0

    oloy.campaign.read_model.repository.campaign_usage:
        alias: OpenLoyalty\Component\Campaign\Infrastructure\Repository\CampaignUsageElasticsearchRepository
        deprecated: The "%service_id%" service is deprecated since 3.1.0

    oloy.user.customer.repository:
        alias: OpenLoyalty\Component\Customer\Domain\CustomerRepository
        deprecated: The "%service_id%" service is deprecated since 3.1.0

    oloy.transaction.repository:
        alias: OpenLoyalty\Component\Transaction\Domain\TransactionRepository
        deprecated: The "%service_id%" service is deprecated since 3.1.0

    oloy.points.account.repository:
        alias: OpenLoyalty\Component\Account\Domain\AccountRepository
        deprecated: The "%service_id%" service is deprecated since 3.1.0

    oloy.transaction.voters.transaction:
        alias: OpenLoyalty\Bundle\TransactionBundle\Security\Voter\TransactionVoter
        deprecated: The "%service_id%" service is deprecated since 3.2.0

    oloy.email.message_factory:
        alias: OpenLoyalty\Bundle\EmailBundle\Service\MessageFactory
        deprecated: The "%service_id%" service is deprecated since 3.2.0
