imports:
    - { resource: services_deprecated.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    broadway.elasticsearch.client:
        class: Elasticsearch\Client
        factory: ['@broadway.elasticsearch.client_factory', create]
        arguments:
            - '%elastica%'

    broadway.elasticsearch.client_factory:
        class: Broadway\ReadModel\ElasticSearch\ElasticSearchClientFactory
        public: false

    Broadway\EventStore\ConcurrencyConflictResolver\BlacklistConcurrencyConflictResolver: ~

    Broadway\Snapshotting\Snapshot\Trigger\EventCountTrigger:
        arguments:
            - '%snapshot_event_count%'

    Broadway\EventStore\Dbal\DBALEventStore:
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@broadway.serializer.payload'
            - '@broadway.serializer.metadata'
            - 'events'
            - false
            - '@broadway.uuid.converter'

    OpenLoyalty\Bundle\CoreBundle\Service\CSVGenerator:
        public: true
        tags: ['controller.service_arguments']

    OpenLoyalty\Bundle\CoreBundle\CSVGenerator\Mapper:
        class: OpenLoyalty\Bundle\CoreBundle\CSVGenerator\Mapper
        factory: [OpenLoyalty\Bundle\CoreBundle\CSVGenerator\Mapper, create]
        arguments: ['%oloy.campaign.bought.export.mappings%']

    OpenLoyalty\Bundle\CoreBundle\Serializer\ReflectionSerializer: ~

    OpenLoyalty\Bundle\CoreBundle\Repository\DBALSnapshotRepository:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
            $payloadSerializer: '@OpenLoyalty\Bundle\CoreBundle\Serializer\ReflectionSerializer'
            $tableName: 'snapshoting'

    oloy.dbal.event.store.concurrency:
        class: OpenLoyalty\Bundle\CoreBundle\EventStore\ConcurrencyDBALEventStore
        arguments:
            - '@Broadway\EventStore\Dbal\DBALEventStore'
            - '@Broadway\EventStore\ConcurrencyConflictResolver\BlacklistConcurrencyConflictResolver'

    oloy.read_model.repository.factory:
        class: OpenLoyalty\Component\Core\Infrastructure\Repository\OloyElasticsearchRepositoryFactory
        arguments:
            - '@broadway.elasticsearch.client'
            - '@OpenLoyalty\Component\Core\Infrastructure\Serializer\SimpleInterfaceSerializer'
            - '%es_max_result_window_size%'

    GuzzleHttp\Client: ~

    OpenLoyalty\Component\Core\Infrastructure\Serializer\SimpleInterfaceSerializer: ~
