services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    test.OpenLoyalty\Bundle\PointsBundle\Import\PointsTransferXmlImporter:
        alias: OpenLoyalty\Bundle\PointsBundle\Import\PointsTransferXmlImporter

