* :doc:`/userguide/segments/creation/anniversary`
* :doc:`/userguide/segments/creation/average_transaction`
* :doc:`/userguide/segments/creation/pos`
* :doc:`/userguide/segments/creation/product_labels`
* :doc:`/userguide/segments/creation/brands`
* :doc:`/userguide/segments/creation/sku`
* :doc:`/userguide/segments/creation/custom_customer`
* :doc:`/userguide/segments/creation/customer_labels`
* :doc:`/userguide/segments/creation/customer_labels_value`
* :doc:`/userguide/segments/creation/last_purchase`
* :doc:`/userguide/segments/creation/purchase_period`
* :doc:`/userguide/segments/creation/transaction_count`
* :doc:`/userguide/segments/creation/transaction_pos`
* :doc:`/userguide/segments/creation/transaction_value`



